project:
  type: website

website:
  title: "Escola dominical que alcança VIDAS"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



